package message

// Deprecated, use `rpc.message.compressed_size` instead
type AttrCompressedSize string // message.compressed_size

func (AttrCompressedSize) Development()    {}
func (AttrCompressedSize) Recommended()    {}
func (AttrCompressedSize) Key() string     { return "message_compressed_size" }
func (a AttrCompressedSize) Value() string { return string(a) }

// Deprecated, use `rpc.message.id` instead
type AttrId string // message.id

func (AttrId) Development()    {}
func (AttrId) Recommended()    {}
func (AttrId) Key() string     { return "message_id" }
func (a AttrId) Value() string { return string(a) }

// Deprecated, use `rpc.message.type` instead
type AttrType string // message.type

func (AttrType) Development()    {}
func (AttrType) Recommended()    {}
func (AttrType) Key() string     { return "message_type" }
func (a AttrType) Value() string { return string(a) }

const TypeSent AttrType = "SENT"
const TypeReceived AttrType = "RECEIVED"

// Deprecated, use `rpc.message.uncompressed_size` instead
type AttrUncompressedSize string // message.uncompressed_size

func (AttrUncompressedSize) Development()    {}
func (AttrUncompressedSize) Recommended()    {}
func (AttrUncompressedSize) Key() string     { return "message_uncompressed_size" }
func (a AttrUncompressedSize) Value() string { return string(a) }

/* State {
    name: "attr.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "ctx": {
            "attributes": [
                {
                    "brief": "Deprecated, use `rpc.message.compressed_size` instead.",
                    "deprecated": {
                        "note": "Replaced by `rpc.message.compressed_size`.",
                        "reason": "renamed",
                        "renamed_to": "rpc.message.compressed_size",
                    },
                    "name": "message.compressed_size",
                    "requirement_level": "recommended",
                    "root_namespace": "message",
                    "stability": "development",
                    "type": "int",
                },
                {
                    "brief": "Deprecated, use `rpc.message.id` instead.",
                    "deprecated": {
                        "note": "Replaced by `rpc.message.id`.",
                        "reason": "renamed",
                        "renamed_to": "rpc.message.id",
                    },
                    "name": "message.id",
                    "requirement_level": "recommended",
                    "root_namespace": "message",
                    "stability": "development",
                    "type": "int",
                },
                {
                    "brief": "Deprecated, use `rpc.message.type` instead.",
                    "deprecated": {
                        "note": "Replaced by `rpc.message.type`.",
                        "reason": "renamed",
                        "renamed_to": "rpc.message.type",
                    },
                    "name": "message.type",
                    "requirement_level": "recommended",
                    "root_namespace": "message",
                    "stability": "development",
                    "type": {
                        "members": [
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "sent",
                                "note": none,
                                "stability": "development",
                                "value": "SENT",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "received",
                                "note": none,
                                "stability": "development",
                                "value": "RECEIVED",
                            },
                        ],
                    },
                },
                {
                    "brief": "Deprecated, use `rpc.message.uncompressed_size` instead.",
                    "deprecated": {
                        "note": "Replaced by `rpc.message.uncompressed_size`.",
                        "reason": "renamed",
                        "renamed_to": "rpc.message.uncompressed_size",
                    },
                    "name": "message.uncompressed_size",
                    "requirement_level": "recommended",
                    "root_namespace": "message",
                    "stability": "development",
                    "type": "int",
                },
            ],
            "root_namespace": "message",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_id",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "attr.go.j2",
        ],
    },
} */
