package exception

// Indicates that the exception is escaping the scope of the span
type AttrEscaped string // exception.escaped

func (AttrEscaped) Stable()         {}
func (AttrEscaped) Recommended()    {}
func (AttrEscaped) Key() string     { return "exception_escaped" }
func (a AttrEscaped) Value() string { return string(a) }

// The exception message
type AttrMessage string // exception.message

func (AttrMessage) Stable()         {}
func (AttrMessage) Recommended()    {}
func (AttrMessage) Key() string     { return "exception_message" }
func (a AttrMessage) Value() string { return string(a) }

// A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG
type AttrStacktrace string // exception.stacktrace

func (AttrStacktrace) Stable()         {}
func (AttrStacktrace) Recommended()    {}
func (AttrStacktrace) Key() string     { return "exception_stacktrace" }
func (a AttrStacktrace) Value() string { return string(a) }

// The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it
type AttrType string // exception.type

func (AttrType) Stable()         {}
func (AttrType) Recommended()    {}
func (AttrType) Key() string     { return "exception_type" }
func (a AttrType) Value() string { return string(a) }

/* State {
    name: "attr.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "ctx": {
            "attributes": [
                {
                    "brief": "Indicates that the exception is escaping the scope of the span.\n",
                    "deprecated": {
                        "note": "It's no longer recommended to record exceptions that are handled and do not escape the scope of a span.\n",
                        "reason": "obsoleted",
                    },
                    "name": "exception.escaped",
                    "requirement_level": "recommended",
                    "root_namespace": "exception",
                    "stability": "stable",
                    "type": "boolean",
                },
                {
                    "brief": "The exception message.",
                    "examples": [
                        "Division by zero",
                        "Can't convert 'int' object to str implicitly",
                    ],
                    "name": "exception.message",
                    "requirement_level": "recommended",
                    "root_namespace": "exception",
                    "stability": "stable",
                    "type": "string",
                },
                {
                    "brief": "A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.\n",
                    "examples": "Exception in thread \"main\" java.lang.RuntimeException: Test exception\\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\\n at com.example.GenerateTrace.methodA(GenerateTrace.java:9)\\n at com.example.GenerateTrace.main(GenerateTrace.java:5)\n",
                    "name": "exception.stacktrace",
                    "requirement_level": "recommended",
                    "root_namespace": "exception",
                    "stability": "stable",
                    "type": "string",
                },
                {
                    "brief": "The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.\n",
                    "examples": [
                        "java.net.ConnectException",
                        "OSError",
                    ],
                    "name": "exception.type",
                    "requirement_level": "recommended",
                    "root_namespace": "exception",
                    "stability": "stable",
                    "type": "string",
                },
            ],
            "root_namespace": "exception",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_id",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "attr.go.j2",
        ],
    },
} */
