package profile

// Describes the interpreter or compiler of a single frame
type AttrFrameType string // profile.frame.type

func (AttrFrameType) Development() {}
func (AttrFrameType) Recommended() {}

/* State {
    name: "attr.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "ctx": {
            "attributes": [
                {
                    "brief": "Describes the interpreter or compiler of a single frame.\n",
                    "examples": [
                        "cpython",
                    ],
                    "name": "profile.frame.type",
                    "requirement_level": "recommended",
                    "root_namespace": "profile",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "[.NET](https://wikipedia.org/wiki/.NET)\n",
                                "deprecated": none,
                                "id": "dotnet",
                                "note": none,
                                "stability": "development",
                                "value": "dotnet",
                            },
                            {
                                "brief": "[JVM](https://wikipedia.org/wiki/Java_virtual_machine)\n",
                                "deprecated": none,
                                "id": "jvm",
                                "note": none,
                                "stability": "development",
                                "value": "jvm",
                            },
                            {
                                "brief": "[Kernel](https://wikipedia.org/wiki/Kernel_(operating_system))\n",
                                "deprecated": none,
                                "id": "kernel",
                                "note": none,
                                "stability": "development",
                                "value": "kernel",
                            },
                            {
                                "brief": "Can be one of but not limited to [C](https://wikipedia.org/wiki/C_(programming_language)), [C++](https://wikipedia.org/wiki/C%2B%2B), [Go](https://wikipedia.org/wiki/Go_(programming_language)) or [Rust](https://wikipedia.org/wiki/Rust_(programming_language)). If possible, a more precise value MUST be used.\n",
                                "deprecated": none,
                                "id": "native",
                                "note": none,
                                "stability": "development",
                                "value": "native",
                            },
                            {
                                "brief": "[Perl](https://wikipedia.org/wiki/Perl)\n",
                                "deprecated": none,
                                "id": "perl",
                                "note": none,
                                "stability": "development",
                                "value": "perl",
                            },
                            {
                                "brief": "[PHP](https://wikipedia.org/wiki/PHP)\n",
                                "deprecated": none,
                                "id": "php",
                                "note": none,
                                "stability": "development",
                                "value": "php",
                            },
                            {
                                "brief": "[Python](https://wikipedia.org/wiki/Python_(programming_language))\n",
                                "deprecated": none,
                                "id": "cpython",
                                "note": none,
                                "stability": "development",
                                "value": "cpython",
                            },
                            {
                                "brief": "[Ruby](https://wikipedia.org/wiki/Ruby_(programming_language))\n",
                                "deprecated": none,
                                "id": "ruby",
                                "note": none,
                                "stability": "development",
                                "value": "ruby",
                            },
                            {
                                "brief": "[V8JS](https://wikipedia.org/wiki/V8_(JavaScript_engine))\n",
                                "deprecated": none,
                                "id": "v8js",
                                "note": none,
                                "stability": "development",
                                "value": "v8js",
                            },
                            {
                                "brief": "[Erlang](https://en.wikipedia.org/wiki/BEAM_(Erlang_virtual_machine))\n",
                                "deprecated": none,
                                "id": "beam",
                                "note": none,
                                "stability": "development",
                                "value": "beam",
                            },
                            {
                                "brief": "[Go](https://wikipedia.org/wiki/Go_(programming_language)),\n",
                                "deprecated": none,
                                "id": "go",
                                "note": none,
                                "stability": "development",
                                "value": "go",
                            },
                            {
                                "brief": "[Rust](https://wikipedia.org/wiki/Rust_(programming_language))\n",
                                "deprecated": none,
                                "id": "rust",
                                "note": none,
                                "stability": "development",
                                "value": "rust",
                            },
                        ],
                    },
                },
            ],
            "root_namespace": "profile",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "attr.go.j2",
        ],
    },
} */
