package vcs

import (
	"github.com/prometheus/client_golang/prometheus"
)

// The number of revisions (commits) a ref (branch) is ahead/behind the branch from the `vcs.ref.base.name` attribute
type RefRevisionsDelta struct {
	*prometheus.GaugeVec
}

func NewRefRevisionsDelta() RefRevisionsDelta {
	labels := []string{"vcs_ref_base_name", "vcs_ref_base_type", "vcs_ref_head_name", "vcs_ref_head_type", "vcs_repository_url_full", "vcs_revision_delta_direction", "vcs_change_id", "vcs_owner_name", "vcs_repository_name", "vcs_provider_name"}
	return RefRevisionsDelta{GaugeVec: prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: "vcs",
		Name:      "ref_revisions_delta",
		Help:      "The number of revisions (commits) a ref (branch) is ahead/behind the branch from the `vcs.ref.base.name` attribute",
	}, labels)}
}

func (m RefRevisionsDelta) With(refBaseName AttrRefBaseName, refBaseType AttrRefBaseType, refHeadName AttrRefHeadName, refHeadType AttrRefHeadType, repositoryUrlFull AttrRepositoryUrlFull, revisionDeltaDirection AttrRevisionDeltaDirection, extra interface {
	AttrVcsChangeId() AttrChangeId
	AttrVcsOwnerName() AttrOwnerName
	AttrVcsRepositoryName() AttrRepositoryName
	AttrVcsProviderName() AttrProviderName
}) prometheus.Gauge {
	if extra == nil {
		extra = RefRevisionsDeltaExtra{}
	}
	return m.WithLabelValues(
		string(refBaseName),
		string(refBaseType),
		string(refHeadName),
		string(refHeadType),
		string(repositoryUrlFull),
		string(revisionDeltaDirection),
		string(extra.AttrVcsChangeId()),
		string(extra.AttrVcsOwnerName()),
		string(extra.AttrVcsRepositoryName()),
		string(extra.AttrVcsProviderName()),
	)
}

type RefRevisionsDeltaExtra struct {
	// The ID of the change (pull request/merge request/changelist) if applicable. This is usually a unique (within repository) identifier generated by the VCS system.
	VcsChangeId AttrChangeId `otel:"vcs.change.id"`
	// The group owner within the version control system.
	VcsOwnerName AttrOwnerName `otel:"vcs.owner.name"`
	// The human readable name of the repository. It SHOULD NOT include any additional identifier like Group/SubGroup in GitLab or organization in GitHub.
	VcsRepositoryName AttrRepositoryName `otel:"vcs.repository.name"`
	// The name of the version control system provider.
	VcsProviderName AttrProviderName `otel:"vcs.provider.name"`
}

func (a RefRevisionsDeltaExtra) AttrVcsChangeId() AttrChangeId   { return a.VcsChangeId }
func (a RefRevisionsDeltaExtra) AttrVcsOwnerName() AttrOwnerName { return a.VcsOwnerName }
func (a RefRevisionsDeltaExtra) AttrVcsRepositoryName() AttrRepositoryName {
	return a.VcsRepositoryName
}
func (a RefRevisionsDeltaExtra) AttrVcsProviderName() AttrProviderName { return a.VcsProviderName }

/*
State {
    name: "metric.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "RefRevisionsDeltaExtra",
        "Instr": "Gauge",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "ref.revisions_delta",
        "Type": "RefRevisionsDelta",
        "attributes": [
            {
                "brief": "The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository.\n",
                "examples": [
                    "my-feature-branch",
                    "tag-1-test",
                ],
                "name": "vcs.ref.base.name",
                "note": "`base` refers to the starting point of a change. For example, `main`\nwould be the base reference of type branch if you've created a new\nreference of type branch from it and created new commits.\n",
                "requirement_level": "required",
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository.\n",
                "examples": [
                    "branch",
                    "tag",
                ],
                "name": "vcs.ref.base.type",
                "note": "`base` refers to the starting point of a change. For example, `main`\nwould be the base reference of type branch if you've created a new\nreference of type branch from it and created new commits.\n",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": "[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)",
                            "deprecated": none,
                            "id": "branch",
                            "note": none,
                            "stability": "development",
                            "value": "branch",
                        },
                        {
                            "brief": "[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)",
                            "deprecated": none,
                            "id": "tag",
                            "note": none,
                            "stability": "development",
                            "value": "tag",
                        },
                    ],
                },
            },
            {
                "brief": "The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository.\n",
                "examples": [
                    "my-feature-branch",
                    "tag-1-test",
                ],
                "name": "vcs.ref.head.name",
                "note": "`head` refers to where you are right now; the current reference at a\ngiven time.\n",
                "requirement_level": "required",
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository.\n",
                "examples": [
                    "branch",
                    "tag",
                ],
                "name": "vcs.ref.head.type",
                "note": "`head` refers to where you are right now; the current reference at a\ngiven time.\n",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": "[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)",
                            "deprecated": none,
                            "id": "branch",
                            "note": none,
                            "stability": "development",
                            "value": "branch",
                        },
                        {
                            "brief": "[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)",
                            "deprecated": none,
                            "id": "tag",
                            "note": none,
                            "stability": "development",
                            "value": "tag",
                        },
                    ],
                },
            },
            {
                "brief": "The [canonical URL](https://support.google.com/webmasters/answer/10347851?hl=en#:~:text=A%20canonical%20URL%20is%20the,Google%20chooses%20one%20as%20canonical.) of the repository providing the complete HTTP(S) address in order to locate and identify the repository through a browser.\n",
                "examples": [
                    "https://github.com/opentelemetry/open-telemetry-collector-contrib",
                    "https://gitlab.com/my-org/my-project/my-projects-project/repo",
                ],
                "name": "vcs.repository.url.full",
                "note": "In Git Version Control Systems, the canonical URL SHOULD NOT include\nthe `.git` extension.\n",
                "requirement_level": "required",
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "The type of revision comparison.\n",
                "examples": [
                    "ahead",
                    "behind",
                ],
                "name": "vcs.revision_delta.direction",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": "How many revisions the change is behind the target ref.",
                            "deprecated": none,
                            "id": "behind",
                            "note": none,
                            "stability": "development",
                            "value": "behind",
                        },
                        {
                            "brief": "How many revisions the change is ahead of the target ref.",
                            "deprecated": none,
                            "id": "ahead",
                            "note": none,
                            "stability": "development",
                            "value": "ahead",
                        },
                    ],
                },
            },
            {
                "brief": "The ID of the change (pull request/merge request/changelist) if applicable. This is usually a unique (within repository) identifier generated by the VCS system.\n",
                "examples": [
                    "123",
                ],
                "name": "vcs.change.id",
                "requirement_level": {
                    "conditionally_required": "if a change is associate with the ref.",
                },
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "The group owner within the version control system.\n",
                "examples": [
                    "my-org",
                    "myteam",
                    "business-unit",
                ],
                "name": "vcs.owner.name",
                "requirement_level": "recommended",
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "The human readable name of the repository. It SHOULD NOT include any additional identifier like Group/SubGroup in GitLab or organization in GitHub.\n",
                "examples": [
                    "semantic-conventions",
                    "my-cool-repo",
                ],
                "name": "vcs.repository.name",
                "note": "Due to it only being the name, it can clash with forks of the same\nrepository if collecting telemetry across multiple orgs or groups in\nthe same backends.\n",
                "requirement_level": "recommended",
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "The name of the version control system provider.\n",
                "examples": [
                    "github",
                    "gitlab",
                    "gitea",
                    "bitbucket",
                ],
                "name": "vcs.provider.name",
                "requirement_level": "opt_in",
                "stability": "development",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": "[GitHub](https://github.com)",
                            "deprecated": none,
                            "id": "github",
                            "note": none,
                            "stability": "development",
                            "value": "github",
                        },
                        {
                            "brief": "[GitLab](https://gitlab.com)",
                            "deprecated": none,
                            "id": "gitlab",
                            "note": none,
                            "stability": "development",
                            "value": "gitlab",
                        },
                        {
                            "brief": "Deprecated, use `gitea` instead.",
                            "deprecated": "Replaced by `gitea`.",
                            "id": "gittea",
                            "note": none,
                            "stability": "development",
                            "value": "gittea",
                        },
                        {
                            "brief": "[Gitea](https://gitea.io)",
                            "deprecated": none,
                            "id": "gitea",
                            "note": none,
                            "stability": "development",
                            "value": "gitea",
                        },
                        {
                            "brief": "[Bitbucket](https://bitbucket.org)",
                            "deprecated": none,
                            "id": "bitbucket",
                            "note": none,
                            "stability": "development",
                            "value": "bitbucket",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "attributes": [
                {
                    "brief": "The human readable name of the repository. It SHOULD NOT include any additional identifier like Group/SubGroup in GitLab or organization in GitHub.\n",
                    "examples": [
                        "semantic-conventions",
                        "my-cool-repo",
                    ],
                    "name": "vcs.repository.name",
                    "note": "Due to it only being the name, it can clash with forks of the same\nrepository if collecting telemetry across multiple orgs or groups in\nthe same backends.\n",
                    "requirement_level": "recommended",
                    "stability": "development",
                    "type": "string",
                },
                {
                    "brief": "The group owner within the version control system.\n",
                    "examples": [
                        "my-org",
                        "myteam",
                        "business-unit",
                    ],
                    "name": "vcs.owner.name",
                    "requirement_level": "recommended",
                    "stability": "development",
                    "type": "string",
                },
                {
                    "brief": "The [canonical URL](https://support.google.com/webmasters/answer/10347851?hl=en#:~:text=A%20canonical%20URL%20is%20the,Google%20chooses%20one%20as%20canonical.) of the repository providing the complete HTTP(S) address in order to locate and identify the repository through a browser.\n",
                    "examples": [
                        "https://github.com/opentelemetry/open-telemetry-collector-contrib",
                        "https://gitlab.com/my-org/my-project/my-projects-project/repo",
                    ],
                    "name": "vcs.repository.url.full",
                    "note": "In Git Version Control Systems, the canonical URL SHOULD NOT include\nthe `.git` extension.\n",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": "string",
                },
                {
                    "brief": "The name of the version control system provider.\n",
                    "examples": [
                        "github",
                        "gitlab",
                        "gitea",
                        "bitbucket",
                    ],
                    "name": "vcs.provider.name",
                    "requirement_level": "opt_in",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "[GitHub](https://github.com)",
                                "deprecated": none,
                                "id": "github",
                                "note": none,
                                "stability": "development",
                                "value": "github",
                            },
                            {
                                "brief": "[GitLab](https://gitlab.com)",
                                "deprecated": none,
                                "id": "gitlab",
                                "note": none,
                                "stability": "development",
                                "value": "gitlab",
                            },
                            {
                                "brief": "Deprecated, use `gitea` instead.",
                                "deprecated": "Replaced by `gitea`.",
                                "id": "gittea",
                                "note": none,
                                "stability": "development",
                                "value": "gittea",
                            },
                            {
                                "brief": "[Gitea](https://gitea.io)",
                                "deprecated": none,
                                "id": "gitea",
                                "note": none,
                                "stability": "development",
                                "value": "gitea",
                            },
                            {
                                "brief": "[Bitbucket](https://bitbucket.org)",
                                "deprecated": none,
                                "id": "bitbucket",
                                "note": none,
                                "stability": "development",
                                "value": "bitbucket",
                            },
                        ],
                    },
                },
                {
                    "brief": "The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository.\n",
                    "examples": [
                        "my-feature-branch",
                        "tag-1-test",
                    ],
                    "name": "vcs.ref.head.name",
                    "note": "`head` refers to where you are right now; the current reference at a\ngiven time.\n",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": "string",
                },
                {
                    "brief": "The ID of the change (pull request/merge request/changelist) if applicable. This is usually a unique (within repository) identifier generated by the VCS system.\n",
                    "examples": [
                        "123",
                    ],
                    "name": "vcs.change.id",
                    "requirement_level": {
                        "conditionally_required": "if a change is associate with the ref.",
                    },
                    "stability": "development",
                    "type": "string",
                },
                {
                    "brief": "The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository.\n",
                    "examples": [
                        "branch",
                        "tag",
                    ],
                    "name": "vcs.ref.head.type",
                    "note": "`head` refers to where you are right now; the current reference at a\ngiven time.\n",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)",
                                "deprecated": none,
                                "id": "branch",
                                "note": none,
                                "stability": "development",
                                "value": "branch",
                            },
                            {
                                "brief": "[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)",
                                "deprecated": none,
                                "id": "tag",
                                "note": none,
                                "stability": "development",
                                "value": "tag",
                            },
                        ],
                    },
                },
                {
                    "brief": "The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository.\n",
                    "examples": [
                        "my-feature-branch",
                        "tag-1-test",
                    ],
                    "name": "vcs.ref.base.name",
                    "note": "`base` refers to the starting point of a change. For example, `main`\nwould be the base reference of type branch if you've created a new\nreference of type branch from it and created new commits.\n",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": "string",
                },
                {
                    "brief": "The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository.\n",
                    "examples": [
                        "branch",
                        "tag",
                    ],
                    "name": "vcs.ref.base.type",
                    "note": "`base` refers to the starting point of a change. For example, `main`\nwould be the base reference of type branch if you've created a new\nreference of type branch from it and created new commits.\n",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)",
                                "deprecated": none,
                                "id": "branch",
                                "note": none,
                                "stability": "development",
                                "value": "branch",
                            },
                            {
                                "brief": "[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)",
                                "deprecated": none,
                                "id": "tag",
                                "note": none,
                                "stability": "development",
                                "value": "tag",
                            },
                        ],
                    },
                },
                {
                    "brief": "The type of revision comparison.\n",
                    "examples": [
                        "ahead",
                        "behind",
                    ],
                    "name": "vcs.revision_delta.direction",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "How many revisions the change is behind the target ref.",
                                "deprecated": none,
                                "id": "behind",
                                "note": none,
                                "stability": "development",
                                "value": "behind",
                            },
                            {
                                "brief": "How many revisions the change is ahead of the target ref.",
                                "deprecated": none,
                                "id": "ahead",
                                "note": none,
                                "stability": "development",
                                "value": "ahead",
                            },
                        ],
                    },
                },
            ],
            "brief": "The number of revisions (commits) a ref (branch) is ahead/behind the branch from the `vcs.ref.base.name` attribute",
            "entity_associations": [
                "vcs.repo",
            ],
            "events": [],
            "id": "metric.vcs.ref.revisions_delta",
            "instrument": "gauge",
            "lineage": {
                "attributes": {
                    "vcs.change.id": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.owner.name": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.provider.name": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.ref.base.name": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.ref.base.type": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.ref.head.name": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.ref.head.type": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.repository.name": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.repository.url.full": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                    "vcs.revision_delta.direction": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.vcs.repository",
                    },
                },
                "provenance": {
                    "path": "https://github.com/open-telemetry/semantic-conventions.git[model]/vcs/metrics.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "vcs.ref.revisions_delta",
            "name": none,
            "note": "This metric should be reported for each `vcs.revision_delta.direction` value. For example if branch `a` is 3 commits behind and 2 commits ahead of `trunk`,\ninstrumentation SHOULD report two measurements: 3 and 2 (both positive numbers) and `vcs.ref.base.name` is set to `trunk`.\n",
            "root_namespace": "vcs",
            "span_kind": none,
            "stability": "development",
            "type": "metric",
            "unit": "{revision}",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "metric.go.j2",
        ],
    },
}
*/
