package db

import (
	"github.com/prometheus/client_golang/prometheus"
)

// Deprecated, use `db.client.connection.count` instead.
type ClientConnectionsUsage struct {
	*prometheus.GaugeVec
}

func NewClientConnectionsUsage() ClientConnectionsUsage {
	labels := []string{"db_client_connections_pool_name", "db_client_connections_state"}
	return ClientConnectionsUsage{GaugeVec: prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: "db",
		Name:      "client_connections_usage",
		Help:      "Deprecated, use `db.client.connection.count` instead.",
	}, labels)}
}

func (m ClientConnectionsUsage) With(clientConnectionsPoolName AttrClientConnectionsPoolName, clientConnectionsState AttrClientConnectionsState, extra interface {
}) prometheus.Gauge {
	if extra == nil {
		extra = ClientConnectionsUsageExtra{}
	}
	return m.WithLabelValues(
		string(clientConnectionsPoolName),
		string(clientConnectionsState),
	)
}

type ClientConnectionsUsageExtra struct {
}

/*
State {
    name: "metric.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "ClientConnectionsUsageExtra",
        "Instr": "Gauge",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "client.connections.usage",
        "Type": "ClientConnectionsUsage",
        "attributes": [
            {
                "brief": "Deprecated, use `db.client.connection.pool.name` instead.",
                "deprecated": {
                    "note": "Replaced by `db.client.connection.pool.name`.",
                    "reason": "renamed",
                    "renamed_to": "db.client.connection.pool.name",
                },
                "examples": [
                    "myDataSource",
                ],
                "name": "db.client.connections.pool.name",
                "requirement_level": "required",
                "stability": "development",
                "type": "string",
            },
            {
                "brief": "Deprecated, use `db.client.connection.state` instead.",
                "deprecated": {
                    "note": "Replaced by `db.client.connection.state`.",
                    "reason": "renamed",
                    "renamed_to": "db.client.connection.state",
                },
                "examples": [
                    "idle",
                ],
                "name": "db.client.connections.state",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "idle",
                            "note": none,
                            "stability": "development",
                            "value": "idle",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "used",
                            "note": none,
                            "stability": "development",
                            "value": "used",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "attributes": [
                {
                    "brief": "Deprecated, use `db.client.connection.state` instead.",
                    "deprecated": {
                        "note": "Replaced by `db.client.connection.state`.",
                        "reason": "renamed",
                        "renamed_to": "db.client.connection.state",
                    },
                    "examples": [
                        "idle",
                    ],
                    "name": "db.client.connections.state",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "idle",
                                "note": none,
                                "stability": "development",
                                "value": "idle",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "used",
                                "note": none,
                                "stability": "development",
                                "value": "used",
                            },
                        ],
                    },
                },
                {
                    "brief": "Deprecated, use `db.client.connection.pool.name` instead.",
                    "deprecated": {
                        "note": "Replaced by `db.client.connection.pool.name`.",
                        "reason": "renamed",
                        "renamed_to": "db.client.connection.pool.name",
                    },
                    "examples": [
                        "myDataSource",
                    ],
                    "name": "db.client.connections.pool.name",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": "string",
                },
            ],
            "brief": "Deprecated, use `db.client.connection.count` instead.",
            "deprecated": {
                "note": "Replaced by `db.client.connection.count`.",
                "reason": "renamed",
                "renamed_to": "db.client.connection.count",
            },
            "events": [],
            "id": "metric.db.client.connections.usage",
            "instrument": "updowncounter",
            "lineage": {
                "attributes": {
                    "db.client.connections.pool.name": {
                        "inherited_fields": [
                            "brief",
                            "deprecated",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.db.metrics.deprecated",
                    },
                    "db.client.connections.state": {
                        "inherited_fields": [
                            "brief",
                            "deprecated",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.db.metrics.deprecated",
                    },
                },
                "provenance": {
                    "path": "https://github.com/open-telemetry/semantic-conventions.git[model]/database/deprecated/metrics-deprecated.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "db.client.connections.usage",
            "name": none,
            "root_namespace": "db",
            "span_kind": none,
            "stability": "development",
            "type": "metric",
            "unit": "{connection}",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "metric.go.j2",
        ],
    },
}
*/
