package cicd

import (
	"github.com/prometheus/client_golang/prometheus"
)

// The number of workers on the CICD system by state.
type WorkerCount struct {
	*prometheus.GaugeVec
	extra WorkerCountExtra
}

func NewWorkerCount() WorkerCount {
	labels := []string{"cicd_worker_state"}
	return WorkerCount{GaugeVec: prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: "cicd",
		Name:      "worker_count",
		Help:      "The number of workers on the CICD system by state.",
	}, labels)}
}

func (m WorkerCount) With(workerState AttrWorkerState, extra interface {
}) prometheus.Gauge {
	if extra == nil {
		extra = m.extra
	}
	return m.WithLabelValues(
		string(workerState),
	)
}

type WorkerCountExtra struct {
}

/*
State {
    name: "metric.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "WorkerCountExtra",
        "Instr": "Gauge",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "worker.count",
        "Type": "WorkerCount",
        "attributes": [
            {
                "brief": "The state of a CICD worker / agent.\n",
                "examples": [
                    "idle",
                    "busy",
                    "down",
                ],
                "name": "cicd.worker.state",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": "The worker is not performing work for the CICD system. It is available to the CICD system to perform work on (online / idle).",
                            "deprecated": none,
                            "id": "available",
                            "note": "Pipelines might have conditions on which workers they are able to run so not every worker might be available to every pipeline.",
                            "stability": "development",
                            "value": "available",
                        },
                        {
                            "brief": "The worker is performing work for the CICD system.",
                            "deprecated": none,
                            "id": "busy",
                            "note": none,
                            "stability": "development",
                            "value": "busy",
                        },
                        {
                            "brief": "The worker is not available to the CICD system (disconnected / down).",
                            "deprecated": none,
                            "id": "offline",
                            "note": none,
                            "stability": "development",
                            "value": "offline",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "attributes": [
                {
                    "brief": "The state of a CICD worker / agent.\n",
                    "examples": [
                        "idle",
                        "busy",
                        "down",
                    ],
                    "name": "cicd.worker.state",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "The worker is not performing work for the CICD system. It is available to the CICD system to perform work on (online / idle).",
                                "deprecated": none,
                                "id": "available",
                                "note": "Pipelines might have conditions on which workers they are able to run so not every worker might be available to every pipeline.",
                                "stability": "development",
                                "value": "available",
                            },
                            {
                                "brief": "The worker is performing work for the CICD system.",
                                "deprecated": none,
                                "id": "busy",
                                "note": none,
                                "stability": "development",
                                "value": "busy",
                            },
                            {
                                "brief": "The worker is not available to the CICD system (disconnected / down).",
                                "deprecated": none,
                                "id": "offline",
                                "note": none,
                                "stability": "development",
                                "value": "offline",
                            },
                        ],
                    },
                },
            ],
            "brief": "The number of workers on the CICD system by state.",
            "events": [],
            "id": "metric.cicd.worker.count",
            "instrument": "updowncounter",
            "lineage": {
                "attributes": {
                    "cicd.worker.state": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.cicd.pipeline",
                    },
                },
                "provenance": {
                    "path": "https://github.com/open-telemetry/semantic-conventions.git[model]/cicd/metrics.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "cicd.worker.count",
            "name": none,
            "root_namespace": "cicd",
            "span_kind": none,
            "stability": "development",
            "type": "metric",
            "unit": "{count}",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "metric.go.j2",
        ],
    },
}
*/
