// Code generated by examples/generate.go; DO NOT EDIT.

package main

import (
	"bufio"
	"fmt"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"log"
	"net/http"
	semhttp "shorez.de/promconv/otel/http"
	"strings"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/hello/{name}", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello %s!", r.PathValue("name"))
	})
	mux.Handle("/metrics", promhttp.Handler())
	handler := semhttp.Instrument(semhttp.Register(prometheus.DefaultRegisterer), mux)
	go func() {
		log.Fatalln(http.ListenAndServe(":4242", handler))
	}()
	if _, err := http.Get("http://localhost:4242/hello/prometheus"); err != nil {
		log.Fatalln(err)
	}
	res, err := http.Get("http://localhost:4242/metrics")
	if err != nil {
		log.Fatalln(err)
	}
	sc := bufio.NewScanner(res.Body)
	for sc.Scan() {
		if strings.HasPrefix(sc.Text(), "http_") {
			fmt.Println(sc.Text())
		}
	}
}
