package dotnet

import (
	"github.com/prometheus/client_golang/prometheus"
)

// The number of garbage collections that have occurred since the process has started.
type GcCollections struct {
	*prometheus.CounterVec
}

func NewGcCollections() GcCollections {
	labels := []string{"dotnet_gc_heap_generation"}
	return GcCollections{CounterVec: prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "dotnet",
		Name:      "gc_collections",
		Help:      "The number of garbage collections that have occurred since the process has started.",
	}, labels)}
}

func (m GcCollections) With(gcHeapGeneration AttrGcHeapGeneration, extra interface {
}) prometheus.Counter {
	if extra == nil {
		extra = GcCollectionsExtra{}
	}
	return m.WithLabelValues(
		string(gcHeapGeneration),
	)
}

type GcCollectionsExtra struct {
}

/*
State {
    name: "metric.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "GcCollectionsExtra",
        "Instr": "Counter",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "gc.collections",
        "Type": "GcCollections",
        "attributes": [
            {
                "brief": "Name of the garbage collector managed heap generation.",
                "examples": [
                    "gen0",
                    "gen1",
                    "gen2",
                ],
                "name": "dotnet.gc.heap.generation",
                "requirement_level": "required",
                "stability": "stable",
                "type": {
                    "allow_custom_values": none,
                    "members": [
                        {
                            "brief": "Generation 0",
                            "deprecated": none,
                            "id": "gen0",
                            "note": none,
                            "stability": "stable",
                            "value": "gen0",
                        },
                        {
                            "brief": "Generation 1",
                            "deprecated": none,
                            "id": "gen1",
                            "note": none,
                            "stability": "stable",
                            "value": "gen1",
                        },
                        {
                            "brief": "Generation 2",
                            "deprecated": none,
                            "id": "gen2",
                            "note": none,
                            "stability": "stable",
                            "value": "gen2",
                        },
                        {
                            "brief": "Large Object Heap",
                            "deprecated": none,
                            "id": "loh",
                            "note": none,
                            "stability": "stable",
                            "value": "loh",
                        },
                        {
                            "brief": "Pinned Object Heap",
                            "deprecated": none,
                            "id": "poh",
                            "note": none,
                            "stability": "stable",
                            "value": "poh",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "attributes": [
                {
                    "brief": "Name of the garbage collector managed heap generation.",
                    "examples": [
                        "gen0",
                        "gen1",
                        "gen2",
                    ],
                    "name": "dotnet.gc.heap.generation",
                    "requirement_level": "required",
                    "stability": "stable",
                    "type": {
                        "allow_custom_values": none,
                        "members": [
                            {
                                "brief": "Generation 0",
                                "deprecated": none,
                                "id": "gen0",
                                "note": none,
                                "stability": "stable",
                                "value": "gen0",
                            },
                            {
                                "brief": "Generation 1",
                                "deprecated": none,
                                "id": "gen1",
                                "note": none,
                                "stability": "stable",
                                "value": "gen1",
                            },
                            {
                                "brief": "Generation 2",
                                "deprecated": none,
                                "id": "gen2",
                                "note": none,
                                "stability": "stable",
                                "value": "gen2",
                            },
                            {
                                "brief": "Large Object Heap",
                                "deprecated": none,
                                "id": "loh",
                                "note": none,
                                "stability": "stable",
                                "value": "loh",
                            },
                            {
                                "brief": "Pinned Object Heap",
                                "deprecated": none,
                                "id": "poh",
                                "note": none,
                                "stability": "stable",
                                "value": "poh",
                            },
                        ],
                    },
                },
            ],
            "brief": "The number of garbage collections that have occurred since the process has started.",
            "events": [],
            "id": "metric.dotnet.gc.collections",
            "instrument": "counter",
            "lineage": {
                "attributes": {
                    "dotnet.gc.heap.generation": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.dotnet",
                    },
                },
                "provenance": {
                    "path": "https://github.com/open-telemetry/semantic-conventions.git[model]/dotnet/runtime-metrics.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "dotnet.gc.collections",
            "name": none,
            "note": "Meter name: `System.Runtime`; Added in: .NET 9.0.\nThis metric uses the [`GC.CollectionCount(int generation)`](https://learn.microsoft.com/dotnet/api/system.gc.collectioncount) API to calculate exclusive collections per generation.\n",
            "root_namespace": "dotnet",
            "span_kind": none,
            "stability": "stable",
            "type": "metric",
            "unit": "{collection}",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "metric.go.j2",
        ],
    },
}
*/
