package v8js

// The type of garbage collection
type AttrGcType string // v8js.gc.type

func (AttrGcType) Development()    {}
func (AttrGcType) Recommended()    {}
func (AttrGcType) Key() string     { return "v8js_gc_type" }
func (a AttrGcType) Value() string { return string(a) }

const GcTypeMajor AttrGcType = "major"
const GcTypeMinor AttrGcType = "minor"
const GcTypeIncremental AttrGcType = "incremental"
const GcTypeWeakcb AttrGcType = "weakcb"

// The name of the space type of heap memory.
// Value can be retrieved from value `space_name` of [`v8.getHeapSpaceStatistics()`]
//
// [`v8.getHeapSpaceStatistics()`]: https://nodejs.org/api/v8.html#v8getheapspacestatistics
type AttrHeapSpaceName string // v8js.heap.space.name

func (AttrHeapSpaceName) Development()    {}
func (AttrHeapSpaceName) Recommended()    {}
func (AttrHeapSpaceName) Key() string     { return "v8js_heap_space_name" }
func (a AttrHeapSpaceName) Value() string { return string(a) }

const HeapSpaceNameNewSpace AttrHeapSpaceName = "new_space"
const HeapSpaceNameOldSpace AttrHeapSpaceName = "old_space"
const HeapSpaceNameCodeSpace AttrHeapSpaceName = "code_space"
const HeapSpaceNameMapSpace AttrHeapSpaceName = "map_space"
const HeapSpaceNameLargeObjectSpace AttrHeapSpaceName = "large_object_space"

/* State {
    name: "attr.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "ctx": {
            "attributes": [
                {
                    "brief": "The type of garbage collection.",
                    "name": "v8js.gc.type",
                    "requirement_level": "recommended",
                    "root_namespace": "v8js",
                    "stability": "development",
                    "type": {
                        "members": [
                            {
                                "brief": "Major (Mark Sweep Compact).",
                                "deprecated": none,
                                "id": "major",
                                "note": none,
                                "stability": "development",
                                "value": "major",
                            },
                            {
                                "brief": "Minor (Scavenge).",
                                "deprecated": none,
                                "id": "minor",
                                "note": none,
                                "stability": "development",
                                "value": "minor",
                            },
                            {
                                "brief": "Incremental (Incremental Marking).",
                                "deprecated": none,
                                "id": "incremental",
                                "note": none,
                                "stability": "development",
                                "value": "incremental",
                            },
                            {
                                "brief": "Weak Callbacks (Process Weak Callbacks).",
                                "deprecated": none,
                                "id": "weakcb",
                                "note": none,
                                "stability": "development",
                                "value": "weakcb",
                            },
                        ],
                    },
                },
                {
                    "brief": "The name of the space type of heap memory.",
                    "name": "v8js.heap.space.name",
                    "note": "Value can be retrieved from value `space_name` of [`v8.getHeapSpaceStatistics()`](https://nodejs.org/api/v8.html#v8getheapspacestatistics)\n",
                    "requirement_level": "recommended",
                    "root_namespace": "v8js",
                    "stability": "development",
                    "type": {
                        "members": [
                            {
                                "brief": "New memory space.",
                                "deprecated": none,
                                "id": "new_space",
                                "note": none,
                                "stability": "development",
                                "value": "new_space",
                            },
                            {
                                "brief": "Old memory space.",
                                "deprecated": none,
                                "id": "old_space",
                                "note": none,
                                "stability": "development",
                                "value": "old_space",
                            },
                            {
                                "brief": "Code memory space.",
                                "deprecated": none,
                                "id": "code_space",
                                "note": none,
                                "stability": "development",
                                "value": "code_space",
                            },
                            {
                                "brief": "Map memory space.",
                                "deprecated": none,
                                "id": "map_space",
                                "note": none,
                                "stability": "development",
                                "value": "map_space",
                            },
                            {
                                "brief": "Large object memory space.",
                                "deprecated": none,
                                "id": "large_object_space",
                                "note": none,
                                "stability": "development",
                                "value": "large_object_space",
                            },
                        ],
                    },
                },
            ],
            "root_namespace": "v8js",
        },
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_id",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "attr.go.j2",
        ],
    },
} */
