package v8js

import (
	"github.com/prometheus/client_golang/prometheus"
)

// Committed size of a heap space.
type HeapSpacePhysicalSize struct {
	*prometheus.GaugeVec
	extra HeapSpacePhysicalSizeExtra
}

func NewHeapSpacePhysicalSize() HeapSpacePhysicalSize {
	labels := []string{AttrHeapSpaceName("").Key()}
	return HeapSpacePhysicalSize{GaugeVec: prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "v8js_heap_space_physical_size",
		Help: "Committed size of a heap space.",
	}, labels)}
}

func (m HeapSpacePhysicalSize) With(heapSpaceName AttrHeapSpaceName, extras ...interface{}) prometheus.Gauge {
	return m.GaugeVec.WithLabelValues(heapSpaceName.Value())
}

// Deprecated: Use [HeapSpacePhysicalSize.With] instead
func (m HeapSpacePhysicalSize) WithLabelValues(lvs ...string) prometheus.Gauge {
	return m.GaugeVec.WithLabelValues(lvs...)
}

type HeapSpacePhysicalSizeExtra struct {
}

/*
State {
    name: "vec.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "HeapSpacePhysicalSizeExtra",
        "Instr": "Gauge",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "heap.space.physical_size",
        "Type": "HeapSpacePhysicalSize",
        "attributes": [
            {
                "brief": "The name of the space type of heap memory.",
                "name": "v8js.heap.space.name",
                "note": "Value can be retrieved from value `space_name` of [`v8.getHeapSpaceStatistics()`](https://nodejs.org/api/v8.html#v8getheapspacestatistics)\n",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "members": [
                        {
                            "brief": "New memory space.",
                            "deprecated": none,
                            "id": "new_space",
                            "note": none,
                            "stability": "development",
                            "value": "new_space",
                        },
                        {
                            "brief": "Old memory space.",
                            "deprecated": none,
                            "id": "old_space",
                            "note": none,
                            "stability": "development",
                            "value": "old_space",
                        },
                        {
                            "brief": "Code memory space.",
                            "deprecated": none,
                            "id": "code_space",
                            "note": none,
                            "stability": "development",
                            "value": "code_space",
                        },
                        {
                            "brief": "Map memory space.",
                            "deprecated": none,
                            "id": "map_space",
                            "note": none,
                            "stability": "development",
                            "value": "map_space",
                        },
                        {
                            "brief": "Large object memory space.",
                            "deprecated": none,
                            "id": "large_object_space",
                            "note": none,
                            "stability": "development",
                            "value": "large_object_space",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "attributes": [
                {
                    "brief": "The name of the space type of heap memory.",
                    "name": "v8js.heap.space.name",
                    "note": "Value can be retrieved from value `space_name` of [`v8.getHeapSpaceStatistics()`](https://nodejs.org/api/v8.html#v8getheapspacestatistics)\n",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "members": [
                            {
                                "brief": "New memory space.",
                                "deprecated": none,
                                "id": "new_space",
                                "note": none,
                                "stability": "development",
                                "value": "new_space",
                            },
                            {
                                "brief": "Old memory space.",
                                "deprecated": none,
                                "id": "old_space",
                                "note": none,
                                "stability": "development",
                                "value": "old_space",
                            },
                            {
                                "brief": "Code memory space.",
                                "deprecated": none,
                                "id": "code_space",
                                "note": none,
                                "stability": "development",
                                "value": "code_space",
                            },
                            {
                                "brief": "Map memory space.",
                                "deprecated": none,
                                "id": "map_space",
                                "note": none,
                                "stability": "development",
                                "value": "map_space",
                            },
                            {
                                "brief": "Large object memory space.",
                                "deprecated": none,
                                "id": "large_object_space",
                                "note": none,
                                "stability": "development",
                                "value": "large_object_space",
                            },
                        ],
                    },
                },
            ],
            "brief": "Committed size of a heap space.",
            "events": [],
            "id": "metric.v8js.heap.space.physical_size",
            "instrument": "updowncounter",
            "lineage": {
                "attributes": {
                    "v8js.heap.space.name": {
                        "inherited_fields": [
                            "brief",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.v8js",
                    },
                },
                "provenance": {
                    "path": "https://github.com/open-telemetry/semantic-conventions.git[model]/v8js/metrics.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "v8js.heap.space.physical_size",
            "name": none,
            "note": "Value can be retrieved from value `physical_space_size` of [`v8.getHeapSpaceStatistics()`](https://nodejs.org/api/v8.html#v8getheapspacestatistics)\n",
            "root_namespace": "v8js",
            "span_kind": none,
            "stability": "development",
            "type": "metric",
            "unit": "By",
        },
        "for_each_attr": <macro for_each_attr>,
        "module": "shorez.de/promconv/otel",
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_id",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "vec.go.j2",
        ],
    },
}
*/
